name: LCDS Scraper

on:
  schedule:
    - cron: '0 */12 * * *' # Every 12 hours
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - run: pip install requests pandas beautifulsoup4 plotly streamlit lxml
    
    - name: Run Scraper
      run: python scraper.py
      
    - name: Commit
      run: |
        git config --global user.name "Auto-Updater"
        git config --global user.email "bot@github.com"
        git add data/lcds_publications.csv
        git commit -m "Update data" || echo "No changes"
        git push
